<?php

namespace AppBundle\Repository;

/**
 * butyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class butyRepository extends \Doctrine\ORM\EntityRepository
{
}
