<?php

namespace AppBundle\Repository;

/**
 * colorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class colorsRepository extends \Doctrine\ORM\EntityRepository
{
}
