<?php

namespace AppBundle\Repository;

/**
 * DangersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DangersRepository extends \Doctrine\ORM\EntityRepository
{
}
