<?php

namespace AppBundle\Repository;

/**
 * rozmiaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rozmiaryRepository extends \Doctrine\ORM\EntityRepository
{
}
