<?php

namespace AppBundle\Repository;

/**
 * substancesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class substancesRepository extends \Doctrine\ORM\EntityRepository
{
}
