<?php

namespace AppBundle\Repository\datalist;

/**
 * _druglikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class _druglikeRepository extends \Doctrine\ORM\EntityRepository
{
}
