<?php

namespace AppBundle\Repository\datalist;

/**
 * _druglike_categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class _druglike_categoryRepository extends \Doctrine\ORM\EntityRepository
{
}
