<?php

namespace AppBundle\Repository\datalist;

/**
 * _kobizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class _kobizeRepository extends \Doctrine\ORM\EntityRepository
{
}
