<?php

namespace AppBundle\Repository\datalist;

/**
 * _reach17Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class _reach17Repository extends \Doctrine\ORM\EntityRepository
{
}
