<?php

namespace AppBundle\Repository\datalist;

/**
 * env_usageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class env_usageRepository extends \Doctrine\ORM\EntityRepository
{
}
