<?php

namespace AppBundle\Repository\datalist;

/**
 * hrcmrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hrcmrRepository extends \Doctrine\ORM\EntityRepository
{
}
