<?php

namespace AppBundle\Repository\datalist;

/**
 * kobizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class kobizeRepository extends \Doctrine\ORM\EntityRepository
{
}
