<?php

namespace AppBundle\Repository\datalist;

/**
 * normableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class normableRepository extends \Doctrine\ORM\EntityRepository
{
}
