<?php

namespace AppBundle\Repository\datalist;

/**
 * p_listRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class p_listRepository extends \Doctrine\ORM\EntityRepository
{
}
