<?php

namespace AppBundle\Repository\datalist;

/**
 * pictogramsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pictogramsRepository extends \Doctrine\ORM\EntityRepository
{
}
