<?php

namespace AppBundle\Repository\datalist;

/**
 * reach14Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reach14Repository extends \Doctrine\ORM\EntityRepository
{
}
