<?php

namespace AppBundle\Repository\datalist;

/**
 * s_listRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class s_listRepository extends \Doctrine\ORM\EntityRepository
{
}
