<?php

namespace AppBundle\Repository\datalist;

/**
 * svhcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class svhcRepository extends \Doctrine\ORM\EntityRepository
{
}
