<?php

namespace AppBundle\Repository\datalist;

/**
 * zzr_zdr_substancesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class zzr_zdr_substancesRepository extends \Doctrine\ORM\EntityRepository
{
}
